version: "3.7"
services:
  aidbox-db:
    image: healthsamurai/aidboxdb:15.3
    pull_policy: always
    ports:
      - "${PGHOSTPORT}:5432"
    volumes:
      - "./pgdata:/data"
    environment:
      POSTGRES_USER: "${PGUSER}"
      POSTGRES_PASSWORD: "${PGPASSWORD}"
      POSTGRES_DB: "${PGDATABASE}"

  aidbox:
    image: healthsamurai/aidboxone:edge
    pull_policy: always
    depends_on: ["aidbox-db"]
    ports:
      - "${AIDBOX_PORT}:${AIDBOX_PORT}"
    env_file:
      - .env
    environment:
      AIDBOX_DEV_MODE: "true"
      PGPORT: 5432
      PGHOST: aidbox-db
      AIDBOX_FHIR_VERSION: "4.0.1"
      AIDBOX_FHIR_SCHEMA_VALIDATION: "true"
      AIDBOX_FHIR_PACKAGES: "hl7.fhir.r4.core#4.0.1:hl7.fhir.uv.ips#1.1.0"
      AIDBOX_VALIDATE_BINDING_URL: "https://tx.fhir.org/r4/ValueSet/$validate-code"
      BOX_FEATURES_VALIDATION_MODE: "fhir-schema"

  node-app:
    hostname: node-app
    build:
      context: ./
      dockerfile: Dockerfile.dev
    ports:
      - 4000:4000
    env_file:
      - .env
    volumes:
      - ./:/usr/src/app
      - ./node_modules:/usr/src/app/node_modules
