apiVersion: v1
kind: Deployment
metadata:
  name: ips-app
  namespace: ips
  labels:
    service: ips-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: ips-app
  template:
    metadata:
      labels:
        app.kubernetes.io/name: ips-app
    spec:
      containers:
        - name: ips-app
          image: ghcr.io/aidbox/app-examples-ips-ig:main
          ports:
            - name: api
              containerPort: 4000
              protocol: TCP
          envFrom:
            - secretRef:
                name: ips-app
      restartPolicy: Always
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
---
apiVersion: v1
kind: Service
metadata:
  name: ips-app
  namespace: ips
  labels:
    service: ips-app
spec:
  ports:
    - name: ips-app
      protocol: TCP
      port: 4000
      targetPort: ips-app
  selector:
    app: ips-app
  type: ClusterIP
